# Generated by Django 3.2 on 2024-02-21 08:13

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastReports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('report', models.FileField(upload_to=dashboard.models.user_reports_path)),
            ],
            options={
                'db_table': 'PastReports',
            },
        ),
        migrations.AlterField(
            model_name='claim',
            name='document',
            field=models.FileField(upload_to=dashboard.models.user_claims_path),
        ),
        migrations.CreateModel(
            name='MedicineTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine', models.CharField(max_length=50)),
                ('morning', models.CharField(max_length=3)),
                ('afternoon', models.CharField(max_length=3)),
                ('evening', models.CharField(max_length=3)),
                ('sos', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MedicineTable',
            },
        ),
    ]
