apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    name: frontend-deployment
    app: frontend
  namespace: medilink
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend-pod
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        name: frontend-pod
        app: frontend
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf-frontend
      containers:
        - name: react-nginx-frontend-server
          image: 2022cfse502/medilink-frontend:final-demo
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true