apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    name: backend-service
    app: backend
  namespace: medilink
spec:
  type: NodePort
  selector:
    name: backend-pod
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP